# Generated by Django 3.2.8 on 2022-07-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elk', '0002_auto_20220704_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesmodel',
            options={'ordering': ['Index_Name']},
        ),
        migrations.RenameField(
            model_name='filesmodel',
            old_name='title',
            new_name='Index_Name',
        ),
    ]
